In [1]:
import numpy as np

In [ ]:
# Crear un array de 1 dimensión con 5 elementos
arr1 = np.array([1, 2, 3, 4, 5, 6])

print('Arreglo 1D: ',arr1)
print('Forma(shape): ',arr1.shape)
print('Número de dimensiones: ',arr1.ndim)
print('Tipo de datos: ',arr1.dtype)


Arreglo 1D:  [1 2 3 4 5 6]
Forma(shape):  (6,)
Número de dimensiones:  1


In [13]:
# cambiar la forma del arreglo a 2 dimensiones 2x3
arr2 = arr1.reshape(2,3)
print('Arreglo 2D: \n',arr2)
print('Forma(shape): ',arr2.shape)
print('Número de dimensiones: ',arr2.ndim)
print('Tipo de datos: ',arr2.dtype)

Arreglo 2D: 
 [[1 2 3]
 [4 5 6]]
Forma(shape):  (2, 3)
Número de dimensiones:  2
Tipo de datos:  int64


In [14]:
# Crear una Matriz de 4x4 con numero aleatorios de 0 y1
matrix = np.random.rand(4,4)

print('Matriz 4x4: \n',matrix)
print('Forma(shape): ',matrix.shape)
print('Número de dimensiones: ',matrix.ndim)
print('Tipo de datos: ',matrix.dtype)

Matriz 4x4: 
 [[0.73988703 0.24377371 0.23310787 0.97730803]
 [0.26086267 0.23827306 0.18054699 0.64098952]
 [0.02680438 0.37168216 0.20374478 0.66287039]
 [0.51950925 0.44852732 0.22073265 0.42451332]]
Forma(shape):  (4, 4)
Número de dimensiones:  2
Tipo de datos:  float64


In [15]:
# Crear matriz apartir de una lista de listas
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Matriz 3x3: \n',arr)
print('Forma(shape): ',arr.shape)
print('Número de dimensiones: ',arr.ndim)
print('Tipo de datos: ',arr.dtype)

Matriz 3x3: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Forma(shape):  (3, 3)
Número de dimensiones:  2
Tipo de datos:  int64


In [17]:
# Crear una matriz de ceros de 3x3 con o
zeros = np.zeros((3,3))
print('Matriz de ceros 3x3: \n',zeros)

Matriz de ceros 3x3: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# Crear una matriz de unos de 3x3 con 1
ones = np.ones((3,3))
ones[1,1] = 5
print('Matriz de unos 3x3: \n',ones)

Matriz de unos 3x3: 
 [[1. 1. 1.]
 [1. 5. 1.]
 [1. 1. 1.]]


In [22]:
# Matriz Identodad 
arr = np.eye(5)
print('Matriz Identidad 3x3: \n',arr)

Matriz Identidad 3x3: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
# Crear un array de 3 dimensión 
arr = np.zeros((2,3,4))
print('Arreglo 3D: \n',arr)

Arreglo 3D: 
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [30]:
arr = np.random.rand(2,5)
print('Arreglo 2x5: \n',arr)

Arreglo 2x5: 
 [[0.64726924 0.76466596 0.71687613 0.58867688 0.0082092 ]
 [0.53920261 0.16902542 0.39259155 0.23741382 0.92299758]]


In [31]:
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6],[7, 8]])
arr1, arr2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [32]:
# Concatenar arreglos Horizontalmente
arr = np.hstack((arr1, arr2))
print('Concatenar Horizontalmente: \n',arr)

Concatenar Horizontalmente: 
 [[1 2 5 6]
 [3 4 7 8]]


In [33]:
# Concatenar arreglos Verticalmente
arr = np.vstack((arr1, arr2))
print('Concatenar Verticalmente: \n',arr)

Concatenar Verticalmente: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [2]:
# Suma de Elementos todos los elementos de un arreglo
arr = np.array([1,2,3,4,5])
print('Suma de elementos: ',arr.sum())

Suma de elementos:  15


In [3]:
# Calcular el promedio de los elementos de un arreglo
arr = np.array([1,2,3,4,5])
print('Promedio de elementos: ',arr.mean())

Promedio de elementos:  3.0


In [4]:
# Calcular la mediana de los elementos de un arreglo
arr = np.array([1,2,3,4,5])
print('Mediana de elementos: ',np.median(arr))

Mediana de elementos:  3.0


In [ ]:
# Calcular el producto de los elementos de un arreglo
arr = np.array([1,2,3,4,5])
print('Producto de elementos: ',arr.prod())#multiplica entre si todos los elementos

Producto de elementos:  120


In [6]:
# Calcular la desviación estandar de los elementos de un arreglo
arr = np.array([1,2,3,4,5])
print('Desviación estandar de elementos: ',arr.std())

Desviación estandar de elementos:  1.4142135623730951


In [7]:
# Calcular la varianza de los elementos de un arreglo
arr = np.array([1,2,3,4,5])
print('Varianza de elementos: ',arr.var())

Varianza de elementos:  2.0


In [ ]:
# Obtener el minimos y maximo de un arreglo
arr = np.array([1,2,3,4,5])
print('Minimo de elementos: ',arr.min())
print('Maximo de elementos: ',arr.max())

Minimo de elementos:  1
Maximo de elementos:  5


In [11]:
# Calcular la suma acumulada de los elementos de un arreglo
arr = np.array([1,2,3,4,5])
print('Suma acumulada de elementos: ',arr.cumsum())

Suma acumulada de elementos:  [ 1  3  6 10 15]


In [12]:
# Suma element-wise de dos arreglos 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print('Suma de arreglos: ',arr1 + arr2)

Suma de arreglos:  [ 7  9 11 13 15]


In [14]:
# resta element-wise de dos arreglos
print('Resta de arreglos: ',arr1 - arr2)
# multiplicación element-wise de dos arreglos
print('Multiplicación de arreglos: ',arr1 * arr2)
# división element-wise de dos arreglos
print('División de arreglos: ',arr1 / arr2)

Resta de arreglos:  [-5 -5 -5 -5 -5]
Multiplicación de arreglos:  [ 6 14 24 36 50]
División de arreglos:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
